Repository ormcamp-fe-3rd/perfect-pick, pull requests merged in 2024-12, with the labels that each got.

#9 [추가]layout/헤더 구현
  index.html
  public/images/header/ico-cart.svg
  public/images/header/ico-login.svg
  public/images/header/ico-logout.svg
  public/images/header/ico-menu-close.svg
  public/images/header/ico-menu.svg
  public/images/header/ico-mypage.svg
  public/images/header/ico-search.svg
  src/App.tsx
  src/assets/react.svg
  src/components/Header.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/HeaderNav.tsx
  src/components/layout/Header/MenuButton.tsx
  src/components/layout/Header/RightMenu.tsx
  src/pages/LoginPage.tsx
  src/router/Router.tsx
  src/styles/index.css
  src/styles/output.css
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: 🎨 Layout

#13 [초안] 제품 상세 페이지 레이아웃
  src/components/productDetail/ProductDescription.tsx
  src/components/productDetail/ProductDetails.tsx
  src/components/productDetail/ProductImages.tsx
  src/components/productDetail/ProductOptions.tsx
  src/pages/ProductDetailPage.tsx
  src/styles/output.css
Labels: 🎨 Layout, 🧑‍🤝‍🧑 TeamReview

#15 [초안] 푸터 레이아웃
  README.md
  index.html
  package-lock.json
  package.json
  public/images/header/ico-cart.svg
  public/images/header/ico-login.svg
  public/images/header/ico-logout.svg
  public/images/header/ico-menu-close.svg
  public/images/header/ico-menu.svg
  public/images/header/ico-mypage.svg
  public/images/header/ico-search.svg
  public/images/home/ico-arrow-bottom-black.svg
  public/images/home/ico-arrow-bottom-white.svg
  public/images/home/ico-arrow-left-black.svg
  public/images/home/ico-arrow-left-white.svg
  public/images/home/ico-arrow-right-black.svg
  public/images/home/ico-arrow-right-white.svg
  public/images/home/ico-arrow-top-black.svg
  public/images/home/ico-arrow-top-white.svg
  src/App.tsx
  src/assets/fonts/BagelFatOne-Regular.ttf
  src/assets/fonts/SUIT-Bold.ttf
  src/assets/fonts/SUIT-ExtraBold.ttf
  src/assets/fonts/SUIT-Regular.ttf
  src/assets/fonts/SUIT-SemiBold.ttf
  src/assets/images/home/banner1.jpg
  src/assets/images/home/banner2.jpg
  src/assets/images/home/banner3.jpg
  src/assets/images/home/banner4.jpg
  src/assets/react.svg
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Home/ArrowButton.tsx
  src/components/Home/MainSlide.tsx
  src/components/Home/TabSlide.tsx
  src/components/Home/TabSlider.tsx
  src/components/layout/Footer/Footer.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/HeaderNav.tsx
  src/components/layout/Header/MenuButton.tsx
  src/components/layout/Header/RightMenu.tsx
  src/index.css
  src/main.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/router/Router.tsx
  src/styles/Footer.css
  src/styles/Header.css
  src/styles/Main.css
  src/styles/index.css
  src/styles/output.css
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: 🎨 Layout, 🧑‍🤝‍🧑 TeamReview

#14 [초안] 메인 페이지 레이아웃
  README.md
  index.html
  package-lock.json
  package.json
  public/images/header/ico-cart.svg
  public/images/header/ico-login.svg
  public/images/header/ico-logout.svg
  public/images/header/ico-menu-close.svg
  public/images/header/ico-menu.svg
  public/images/header/ico-mypage.svg
  public/images/header/ico-search.svg
  public/images/home/ico-arrow-bottom-black.svg
  public/images/home/ico-arrow-bottom-white.svg
  public/images/home/ico-arrow-left-black.svg
  public/images/home/ico-arrow-left-white.svg
  public/images/home/ico-arrow-right-black.svg
  public/images/home/ico-arrow-right-white.svg
  public/images/home/ico-arrow-top-black.svg
  public/images/home/ico-arrow-top-white.svg
  src/App.tsx
  src/assets/fonts/BagelFatOne-Regular.ttf
  src/assets/fonts/SUIT-Bold.ttf
  src/assets/fonts/SUIT-ExtraBold.ttf
  src/assets/fonts/SUIT-Regular.ttf
  src/assets/fonts/SUIT-SemiBold.ttf
  src/assets/images/home/banner1.jpg
  src/assets/images/home/banner2.jpg
  src/assets/images/home/banner3.jpg
  src/assets/images/home/banner4.jpg
  src/assets/react.svg
  src/components/Header.tsx
  src/components/Home/ArrowButton.tsx
  src/components/Home/MainSlide.tsx
  src/components/Home/TabSlide.tsx
  src/components/Home/TabSlider.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/HeaderNav.tsx
  src/components/layout/Header/MenuButton.tsx
  src/components/layout/Header/RightMenu.tsx
  src/index.css
  src/main.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/router/Router.tsx
  src/styles/Footer.css
  src/styles/Header.css
  src/styles/Main.css
  src/styles/index.css
  src/styles/output.css
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: 🎨 Layout, 🧑‍🤝‍🧑 TeamReview

#17 [추가]layout/checkbox 구현
  src/components/productSearch/CheckBox.tsx
Labels: 🎨 Layout, 🧑‍🤝‍🧑 TeamReview

#16 [초안] 회원가입 페이지 레이아웃
  README.md
  index.html
  package-lock.json
  package.json
  public/images/header/ico-cart.svg
  public/images/header/ico-login.svg
  public/images/header/ico-logout.svg
  public/images/header/ico-menu-close.svg
  public/images/header/ico-menu.svg
  public/images/header/ico-mypage.svg
  public/images/header/ico-search.svg
  public/images/home/ico-arrow-bottom-black.svg
  public/images/home/ico-arrow-bottom-white.svg
  public/images/home/ico-arrow-left-black.svg
  public/images/home/ico-arrow-left-white.svg
  public/images/home/ico-arrow-right-black.svg
  public/images/home/ico-arrow-right-white.svg
  public/images/home/ico-arrow-top-black.svg
  public/images/home/ico-arrow-top-white.svg
  public/images/register/ico-check-gray.svg
  public/images/register/ico-check-green.svg
  src/App.tsx
  src/assets/fonts/BagelFatOne-Regular.ttf
  src/assets/fonts/SUIT-Bold.ttf
  src/assets/fonts/SUIT-ExtraBold.ttf
  src/assets/fonts/SUIT-Regular.ttf
  src/assets/fonts/SUIT-SemiBold.ttf
  src/assets/images/home/banner1.jpg
  src/assets/images/home/banner2.jpg
  src/assets/images/home/banner3.jpg
  src/assets/images/home/banner4.jpg
  src/assets/react.svg
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Home/ArrowButton.tsx
  src/components/Home/MainSlide.tsx
  src/components/Home/TabSlide.tsx
  src/components/Home/TabSlider.tsx
  src/components/layout/Footer/Footer.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/HeaderNav.tsx
  src/components/layout/Header/MenuButton.tsx
  src/components/layout/Header/RightMenu.tsx
  src/components/register/RegisterInput.tsx
  src/components/register/RegisterMain.tsx
  src/index.css
  src/main.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
  src/router/Router.tsx
  src/styles/Footer.css
  src/styles/Header.css
  src/styles/Main.css
  src/styles/index.css
  src/styles/output.css
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: 🎨 Layout, 🧑‍🤝‍🧑 TeamReview

#18 [초안] 장바구니 페이지 레이아웃
  package-lock.json
  package.json
  src/components/cart/CartCheckBox.tsx
  src/components/cart/CartTable.tsx
  src/components/cart/CustomStepper.tsx
  src/pages/CartPage.tsx
  src/styles/output.css
Labels: ✨ Feature, 🎨 Layout, 🧑‍🤝‍🧑 TeamReview

#19 [초안] 비회원 주문조회 페이지 레이아웃
  README.md
  index.html
  public/images/header/ico-cart.svg
  public/images/header/ico-login.svg
  public/images/header/ico-logout.svg
  public/images/header/ico-menu-close.svg
  public/images/header/ico-menu.svg
  public/images/header/ico-mypage.svg
  public/images/header/ico-search.svg
  src/App.tsx
  src/assets/fonts/BagelFatOne-Regular.ttf
  src/assets/fonts/SUIT-Bold.ttf
  src/assets/fonts/SUIT-ExtraBold.ttf
  src/assets/fonts/SUIT-Regular.ttf
  src/assets/fonts/SUIT-SemiBold.ttf
  src/assets/react.svg
  src/components/Header.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/HeaderNav.tsx
  src/components/layout/Header/MenuButton.tsx
  src/components/layout/Header/RightMenu.tsx
  src/components/non-member/BackMainButton.tsx
  src/components/non-member/NonMemberCartList.tsx
  src/components/non-member/NonMemberInfo.tsx
  src/components/non-member/NonMemberSectionTitle.tsx
  src/index.css
  src/main.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/NonMemberPage.tsx
  src/router/Router.tsx
  src/styles/Footer.css
  src/styles/Header.css
  src/styles/Main.css
  src/styles/index.css
  src/styles/output.css
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: 🎨 Layout, 🧑‍🤝‍🧑 TeamReview

#26 [수정] 장바구니 페이지: 컴포넌트 레이아웃 수정
  src/components/cart/CartCheckBox.tsx
  src/components/cart/CartTable.tsx
  src/pages/CartPage.tsx
  src/styles/output.css
Labels: 🎨 Layout

#27 [수정] 결제페이지: 컴포넌트 레이아웃 수정
  src/components/payment/PaymentOptions.tsx
  src/components/payment/ShippingAddress.tsx
  src/components/payment/ShippingInput.tsx
  src/pages/PaymentPage.tsx
  src/styles/output.css
Labels: 🎨 Layout

#25 [수정] 제품 상세 페이지: 컴포넌트 분리, 페이지 구조 수정
  src/components/productDetail/CustomStepper.tsx
  src/components/productDetail/ProductDetails.tsx
  src/components/productDetail/ProductImages.tsx
  src/components/productDetail/ProductOptions.tsx
  src/components/productDetail/SelectOptions.tsx
  src/pages/ProductDetailPage.tsx
  src/styles/output.css
Labels: 🎨 Layout, 🧑‍🤝‍🧑 TeamReview

#23 [수정]회원가입 페이지 레이아웃
  src/components/register/RegisterForm.tsx
  src/components/register/RegisterInput.tsx
  src/components/register/RegisterMain.tsx
  src/components/register/RegisterSuccess.tsx
  src/styles/output.css
  src/utils/validator.ts
Labels: 🎨 Layout, 📝Review, 🧑‍🤝‍🧑 TeamReview

#36 [수정] 장바구니 페이지: 피드백 반영
  src/components/cart/CartCheckBox.tsx
  src/components/cart/CartListItem.tsx
  src/components/cart/CartTable.tsx
  src/constants/option.ts
  src/pages/CartPage.tsx
Labels: 🎨 Layout

#34 [추가] 제품 상세 페이지: 옵션별 가격 계산 기능 추가, 컴포넌트 분리
  src/components/productDetail/ActionButton.tsx
  src/components/productDetail/CustomStepper.tsx
  src/components/productDetail/Modal.tsx
  src/components/productDetail/ProductDescription.tsx
  src/components/productDetail/ProductImages.tsx
  src/components/productDetail/ProductOptions.tsx
  src/components/productDetail/SelectOption.tsx
  src/components/productDetail/SelectOptions.tsx
  src/styles/output.css
Labels: ✨ Feature, 🎨 Layout, 🧑‍🤝‍🧑 TeamReview

#29 [수정] 비회원 구매조회 페이지 키값 삭제
  src/components/non-member/NonMemberCartList.tsx
  src/components/non-member/NonMemberInfo.tsx
Labels: 🎨 Layout, 🧑‍🤝‍🧑 TeamReview

#22 [초안]로그인 페이지 레이아웃
  README.md
  index.html
  package-lock.json
  package.json
  public/images/header/ico-cart.svg
  public/images/header/ico-login.svg
  public/images/header/ico-logout.svg
  public/images/header/ico-menu-close.svg
  public/images/header/ico-menu.svg
  public/images/header/ico-mypage.svg
  public/images/header/ico-search.svg
  public/images/home/ico-arrow-bottom-black.svg
  public/images/home/ico-arrow-bottom-white.svg
  public/images/home/ico-arrow-left-black.svg
  public/images/home/ico-arrow-left-white.svg
  public/images/home/ico-arrow-right-black.svg
  public/images/home/ico-arrow-right-white.svg
  public/images/home/ico-arrow-top-black.svg
  public/images/home/ico-arrow-top-white.svg
  src/App.tsx
  src/assets/fonts/BagelFatOne-Regular.ttf
  src/assets/fonts/SUIT-Bold.ttf
  src/assets/fonts/SUIT-ExtraBold.ttf
  src/assets/fonts/SUIT-Regular.ttf
  src/assets/fonts/SUIT-SemiBold.ttf
  src/assets/images/home/banner1.jpg
  src/assets/images/home/banner2.jpg
  src/assets/images/home/banner3.jpg
  src/assets/images/home/banner4.jpg
  src/assets/react.svg
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Home/ArrowButton.tsx
  src/components/Home/MainSlide.tsx
  src/components/Home/TabSlide.tsx
  src/components/Home/TabSlider.tsx
  src/components/layout/Footer/Footer.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/HeaderNav.tsx
  src/components/layout/Header/MenuButton.tsx
  src/components/layout/Header/RightMenu.tsx
  src/components/login/LoginButton.tsx
  src/components/login/LoginInput.tsx
  src/components/login/LoginTitle.tsx
  src/index.css
  src/main.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/router/Router.tsx
  src/styles/Footer.css
  src/styles/Header.css
  src/styles/Main.css
  src/styles/index.css
  src/styles/output.css
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: 🎨 Layout, 🧑‍🤝‍🧑 TeamReview

#30 [초안] main - 제품 상세 페이지 레이아웃 추가
  src/components/productDetail/ActionButton.tsx
  src/components/productDetail/CustomStepper.tsx
  src/components/productDetail/Modal.tsx
  src/components/productDetail/ProductDescription.tsx
  src/components/productDetail/ProductImages.tsx
  src/components/productDetail/ProductOptions.tsx
  src/components/productDetail/SelectOption.tsx
  src/pages/ProductDetailPage.tsx
  src/styles/output.css
Labels: 🎨 Layout

#31 [초안] main - 장바구니 페이지 레이아웃 추가
  package-lock.json
  package.json
  src/components/cart/CartCheckBox.tsx
  src/components/cart/CartListItem.tsx
  src/components/cart/CartTable.tsx
  src/components/cart/CustomStepper.tsx
  src/constants/option.ts
  src/pages/CartPage.tsx
  src/styles/output.css
Labels: 🎨 Layout, 📝Review

#32 [초안] main - 결제 페이지 레이아웃 추가
  package-lock.json
  package.json
  public/images/home/ico-arrow-bottom-black.svg
  public/images/home/ico-arrow-bottom-white.svg
  public/images/home/ico-arrow-left-black.svg
  public/images/home/ico-arrow-left-white.svg
  public/images/home/ico-arrow-right-black.svg
  public/images/home/ico-arrow-right-white.svg
  public/images/home/ico-arrow-top-black.svg
  public/images/home/ico-arrow-top-white.svg
  public/images/register/ico-check-gray.svg
  public/images/register/ico-check-green.svg
  src/assets/images/home/banner1.jpg
  src/assets/images/home/banner2.jpg
  src/assets/images/home/banner3.jpg
  src/assets/images/home/banner4.jpg
  src/components/Footer.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/HeaderNav.tsx
  src/components/layout/Header/MenuButton.tsx
  src/components/layout/Header/RightMenu.tsx
  src/components/payment/CustomCheckBox.tsx
  src/components/payment/DiscountApply.tsx
  src/components/payment/OrderDetails.tsx
  src/components/payment/PaymentButtonModal.tsx
  src/components/payment/PaymentOptions.tsx
  src/components/payment/PaymentPrivacyModal.tsx
  src/components/payment/ShippingAddress.tsx
  src/components/payment/ShippingInput.tsx
  src/pages/HomePage.tsx
  src/pages/PaymentPage.tsx
  src/router/Router.tsx
  src/styles/index.css
  src/styles/output.css
  tailwind.config.js
Labels: 🎨 Layout

#37 [수정]회원가입 메인 머지
  src/components/Home/ArrowButton.tsx
  src/components/Home/MainSlide.tsx
  src/components/Home/TabSlide.tsx
  src/components/Home/TabSlider.tsx
  src/components/layout/Footer/Footer.tsx
  src/components/layout/Header/HeaderNav.tsx
  src/components/layout/Header/RightMenu.tsx
  src/components/register/RegisterForm.tsx
  src/components/register/RegisterInput.tsx
  src/components/register/RegisterMain.tsx
  src/components/register/RegisterSuccess.tsx
  src/pages/HomePage.tsx
  src/pages/RegisterPage.tsx
  src/styles/output.css
  src/utils/validator.ts
Labels: 🎨 Layout

#38 [수정] 로그인 페이지 메인 병합
  src/components/login/LoginButton.tsx
  src/components/login/LoginInput.tsx
  src/components/login/LoginTitle.tsx
  src/pages/LoginPage.tsx
  src/styles/index.css
  src/styles/output.css
Labels: 🎨 Layout

#39 [수정]비회원 구매조회 페이지 메인 머지
  src/components/non-member/BackMainButton.tsx
  src/components/non-member/NonMemberCartList.tsx
  src/components/non-member/NonMemberInfo.tsx
  src/components/non-member/NonMemberSectionTitle.tsx
  src/pages/NonMemberPage.tsx
  src/styles/index.css
  src/styles/output.css
Labels: 🎨 Layout

#33 [초안] main - 마이페이지 레이아웃 추가
  src/assets/images/mypage/card-img.png
  src/components/layout/Header/HeaderNav.tsx
  src/components/layout/Header/RightMenu.tsx
  src/components/myPage/OrderHistory.tsx
  src/components/myPage/UserInfo.tsx
  src/components/myPage/UserInfoInput.tsx
  src/components/myPage/WelcomeMessage.tsx
  src/pages/HomePage.tsx
  src/pages/MyPage.tsx
  src/styles/output.css
Labels: 🎨 Layout

#40 [수정] 헤더, 푸터 레이아웃 메인 머지
  src/components/productSearch/CheckBox.tsx
  src/styles/output.css
Labels: 🎨 Layout

#28 [초안]상품 검색 페이지 레이아웃
  README.md
  index.html
  package-lock.json
  package.json
  public/images/Products/downIcon.svg
  public/images/Products/galaxy-side.png
  public/images/Products/tablet-side.png
  public/images/Products/werable-side.png
  public/images/header/ico-cart.svg
  public/images/header/ico-login.svg
  public/images/header/ico-logout.svg
  public/images/header/ico-menu-close.svg
  public/images/header/ico-menu.svg
  public/images/header/ico-mypage.svg
  public/images/header/ico-search.svg
  src/App.tsx
  src/assets/fonts/BagelFatOne-Regular.ttf
  src/assets/fonts/SUIT-Bold.ttf
  src/assets/fonts/SUIT-ExtraBold.ttf
  src/assets/fonts/SUIT-Regular.ttf
  src/assets/fonts/SUIT-SemiBold.ttf
  src/assets/react.svg
  src/components/Header.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/HeaderNav.tsx
  src/components/layout/Header/MenuButton.tsx
  src/components/layout/Header/RightMenu.tsx
  src/components/productSearch/BottomSheet/BottomSheet.tsx
  src/components/productSearch/BottomSheet/BottomSheetContainer.tsx
  src/components/productSearch/BottomSheet/BottomSheetFeature.tsx
  src/components/productSearch/Feature/CheckBox.tsx
  src/components/productSearch/Feature/DropdownMenu.tsx
  src/components/productSearch/Feature/InputString.tsx
  src/components/productSearch/Feature/SearchSide.tsx
  src/components/productSearch/Options/DefaultOption.tsx
  src/components/productSearch/Options/MobileOption.tsx
  src/components/productSearch/Product/Product.tsx
  src/components/productSearch/Product/ProductBtn.tsx
  src/components/productSearch/Product/ProductContainer.tsx
  src/constants/optionsData.json
  src/constants/optionsData.ts
  src/index.css
  src/main.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/ProductSearchPage.tsx
  src/pages/Search/MobileSearchPage.tsx
  src/pages/Search/NotebookSearchPage.tsx
  src/pages/Search/TabletSearchPage.tsx
  src/pages/Search/WearableSearchPage.tsx
  src/router/Router.tsx
  src/styles/Footer.css
  src/styles/Header.css
  src/styles/Main.css
  src/styles/index.css
  src/styles/output.css
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: 🎨 Layout, 📝Review, 🧑‍🤝‍🧑 TeamReview

#44 [초안] 상품 검색 페이지, 상품 통합 페이지 초안 레이아웃 main merge
  package-lock.json
  package.json
  public/images/Products/downIcon.svg
  public/images/Products/galaxy-side.png
  public/images/Products/tablet-side.png
  public/images/Products/werable-side.png
  src/components/productSearch/BottomSheet/BottomSheet.tsx
  src/components/productSearch/BottomSheet/BottomSheetContainer.tsx
  src/components/productSearch/BottomSheet/BottomSheetFeature.tsx
  src/components/productSearch/Feature/CheckBox.tsx
  src/components/productSearch/Feature/DropdownMenu.tsx
  src/components/productSearch/Feature/InputString.tsx
  src/components/productSearch/Feature/SearchInput.tsx
  src/components/productSearch/Feature/SearchSide.tsx
  src/components/productSearch/Options/DefaultOption.tsx
  src/components/productSearch/Options/MobileOption.tsx
  src/components/productSearch/Product/Product.tsx
  src/components/productSearch/Product/ProductBtn.tsx
  src/components/productSearch/Product/ProductContainer.tsx
  src/constants/optionsData.json
  src/constants/optionsData.ts
  src/main.tsx
  src/pages/ProductSearchPage.tsx
  src/pages/Search/MobileSearchPage.tsx
  src/pages/Search/NotebookSearchPage.tsx
  src/pages/Search/TabletSearchPage.tsx
  src/pages/Search/TotalSearchPage.tsx
  src/pages/Search/WearableSearchPage.tsx
  src/pages/TotalSearchPage.tsx
  src/router/Router.tsx
  src/styles/output.css
  tailwind.config.js
Labels: 🎨 Layout

#47 [추가] 제품 상세 페이지 - 서버 데이터 불러오기, 라우터 설정
  firebase.json
  index-backup.html
  src/App.tsx
  src/components/payment/CustomCheckBox.tsx
  src/components/productDetail/ProductDescription.tsx
  src/components/productDetail/ProductImages.tsx
  src/components/productDetail/ProductOptions.tsx
  src/firebase.ts
  src/hooks/useProducts.ts
  src/main.tsx
  src/pages/ProductDetailPage.tsx
  src/pages/ProductSearchPage.tsx
  src/router/Router.tsx
  src/styles/output.css
  src/vite-env.d.ts
  tsconfig.json
Labels: ✨ Feature, 📬 API

#59 [추가] main - 마이페이지 : 도로명 주소 검색 기능 추가
  .env.example
  firebase.json
  index-backup.html
  src/App.tsx
  src/components/myPage/OrderHistory.tsx
  src/components/myPage/SearchAddress.tsx
  src/components/myPage/UserInfo.tsx
  src/components/myPage/UserInfoInput.tsx
  src/components/payment/CustomCheckBox.tsx
  src/firebase.ts
  src/main.tsx
  src/styles/output.css
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature

#60 [추가] main - 제품 상세 페이지 서버 데이터 연결
  src/components/productDetail/ProductDescription.tsx
  src/components/productDetail/ProductImages.tsx
  src/components/productDetail/ProductOptions.tsx
  src/hooks/useProducts.ts
  src/pages/ProductDetailPage.tsx
  src/pages/ProductSearchPage.tsx
  src/router/Router.tsx
  src/styles/output.css
  src/vite-env.d.ts
Labels: ✨ Feature, 📬 API

#62 [추가] 제품 상세 페이지: 장바구니 담기 기능(db 추가)
  .env.example
  src/components/cart/CartListItem.tsx
  src/components/cart/CustomStepper.tsx
  src/components/common/CustomStepper.tsx
  src/components/productDetail/ActionButton.tsx
  src/components/productDetail/ProductImages.tsx
  src/components/productDetail/ProductOptions.tsx
  src/components/productDetail/SelectOption.tsx
  src/firebase.ts
  src/pages/LoginPage.tsx
  src/pages/ProductDetailPage.tsx
  src/styles/output.css
  src/types.ts
Labels: ✨ Feature, 📬 API, 📝Review

#64 [추가] 장바구니 페이지: 서버 데이터 연결 및 기능 구현
  .gitignore
  src/components/cart/CartListItem.tsx
  src/components/cart/CartTable.tsx
  src/components/common/CustomStepper.tsx
  src/styles/output.css
  src/types.ts
  src/vite-env.d.ts
Labels: ✨ Feature, 📬 API

#63 [수정] 제품 상세 페이지: 장바구니 담기 기능 개선
  src/components/cart/CartTable.tsx
  src/components/productDetail/ActionButton.tsx
  src/components/productDetail/Modal.tsx
  src/components/productDetail/ProductOptions.tsx
  src/components/productDetail/SelectOption.tsx
  src/firebase.ts
  src/pages/ProductDetailPage.tsx
Labels: ✨ Feature

#66 [수정] 결제페이지: 데이터 연결 및 기능 추가
  .firebase/hosting..cache
  .firebase/hosting.ZGlzdA.cache
  .firebase/hosting.c3Jj.cache
  .firebase/hosting.cHVibGlj.cache
  src/components/Home/TabSlider.tsx
  src/components/cart/CartListItem.tsx
  src/components/cart/CartTable.tsx
  src/components/common/SearchAddress.tsx
  src/components/myPage/SearchAddress.tsx
  src/components/myPage/UserInfo.tsx
  src/components/myPage/WelcomeMessage.tsx
  src/components/payment/DiscountApply.tsx
  src/components/payment/OrderDetails.tsx
  src/components/payment/PaymentButtonModal.tsx
  src/components/payment/PaymentOptions.tsx
  src/components/payment/ShippingAddress.tsx
  src/components/payment/ShippingInput.tsx
  src/components/productDetail/ActionButton.tsx
  src/components/productDetail/ProductDescription.tsx
  src/components/productDetail/ProductImages.tsx
  src/components/productDetail/ProductOptions.tsx
  src/constants/option.ts
  src/constants/optionsData.ts
  src/firebase.ts
  src/hooks/useLocalStorage.ts
  src/hooks/useProducts.ts
  src/pages/CartPage.tsx
  src/pages/PaymentPage.tsx
  src/pages/ProductDetailPage.tsx
  src/styles/output.css
  src/types.ts
Labels: ✨ Feature, 📬 API, 📝Review

#67 [수정] 상품 검색 페이지 기능 및 마이페이지 수정
  public/images/Products/wearable-side.png
  src/components/myPage/UserInfo.tsx
  src/components/productSearch/BottomSheet/BottomSheetFeature.tsx
  src/components/productSearch/CheckBox.tsx
  src/components/productSearch/Feature/CheckBox.tsx
  src/components/productSearch/Feature/InputString.tsx
  src/components/productSearch/Feature/SearchInput.tsx
  src/components/productSearch/Options/DefaultOption.tsx
  src/components/productSearch/Options/MobileOption.tsx
  src/components/productSearch/Options/SharedOption.tsx
  src/components/productSearch/Product/Product.tsx
  src/components/productSearch/Product/ProductListPage.tsx
  src/components/productSearch/utils/filterProduct.tsx
  src/constants/optionsData.json
  src/constants/optionsData.ts
  src/firebase.ts
  src/pages/ProductSearchPage.tsx
  src/pages/Search/MobileSearchPage.tsx
  src/pages/Search/NotebookSearchPage.tsx
  src/pages/Search/TabletSearchPage.tsx
  src/pages/Search/TotalSearchPage.tsx
  src/pages/Search/WearableSearchPage.tsx
Labels: ✨ Feature, 📬 API, 📝Review

#68 [수정] 상세페이지: 제품 스펙 탭 추가 및 버그 수정
  src/components/myPage/OrderHistory.tsx
  src/components/myPage/UserInfo.tsx
  src/components/payment/ShippingAddress.tsx
  src/components/productDetail/ProductDescription.tsx
  src/components/productDetail/ProductOptions.tsx
  src/components/productSearch/Product/ProductListPage.tsx
  src/pages/RecommendPage.tsx
Labels: 🐞 BugFix, ✨ Feature

#69 [수정] 상품 검색페이지, 통합 검색 페이지, 기타 버그 및 오류 수정
  README.md
  public/images/Products/galaxy-side.png
  public/images/Products/tablet-side.png
  public/images/Products/wearable-side.png
  src/components/Home/MainSlide.tsx
  src/components/myPage/UserInfo.tsx
  src/components/productSearch/BottomSheet/BottomSheetFeature.tsx
  src/components/productSearch/Feature/SearchInput.tsx
  src/components/productSearch/Feature/SearchSide.tsx
  src/components/productSearch/Options/MobileOption.tsx
  src/components/productSearch/Options/SharedOption.tsx
Labels: 🐞 BugFix, ✨ Feature
